icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "#00000000"
info_bg = "#00000000"
good_bg = "#00000000"
good_fg = "#ffffff"
warning_bg = "#00000000"
warning_fg = "#ffffff"
critical_bg = "#00000000"
separator = "〈"
separator_bg = "#00000000"
separator_fg = "#ffffff"
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#ffffff"

[[block]]
block = "custom"
command = "echo ' '$(whoami)@$(hostname)"

[[block]]
block = "disk_space"
alias = ""
interval = 1

[[block]]
block = "disk_space"
path = "/home"
alias = ""
interval = 1

[[block]]
block = "custom"
command = "${HOME}/.files/scripts/wrappers/vpn"
interval = 1

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
speed_up = false
speed_down = false
graph_up = false
graph_down = false

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{Mup}%"
interval = 1

[[block]]
block = "cpu"

[[block]]
block = "custom"
command = "${HOME}/.files/scripts/wrappers/battery"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %T"
