# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
console_title_template: "({{.UserName}}@{{.HostName}}) {{.Shell}}:{{.PWD}}"
blocks:
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        foreground: "#c83089"
        style: plain
        template: "<b>\ue602</b> "
      - type: exit
        foreground: "#ff0000"
        style: plain
        # Whitelist SIGPIPE from being shown, as they aren't real errors to even make any concern.
        template: "{{ if and (gt .Code 0) (ne .Code 141) }}<b>{{ .Code }}</b>{{ end }} "
      - type: text
        foreground: "#86c1da"
        style: plain
        template: "<b>{{ .Shell }}</b> "
      - type: python
        foreground: white
        properties:
          fetch_version: false
        style: plain
        template: "{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ .Full }}{{ end }} "
      - type: text
        foreground: "#d861a6"
        style: plain
        template: "<b>\ue602</b> "
      - type: root
        foreground: red
        style: plain
        template: " % "
      - type: session
        style: plain
        template: "<#005bbb><b>{{ .UserName }}</b></><white>@</><#ffd500><b>{{ .HostName }}</b></> "
      - type: path
        foreground: "#da3636"
        properties:
          style: letter
        style: plain
        template: "<white>in </><b>{{ .Path }}</b> "
      - type: git
        foreground: "#3ab038"
        style: plain
        template: "<white>on</> <b>{{ .HEAD }}</b> "
      - type: executiontime
        foreground: white
        properties:
          style: round
          threshold: 3000 # 3 seconds
        style: plain
        template: "took <#2adcd3><b>{{ .FormattedMs }}</b></> "
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: exit
        foreground: lightGreen
        foreground_templates:
          - "{{ if (gt .Code 0) (ne .Code 141) }}#ff0000{{ end }}"
        properties:
          always_enabled: true
        style: plain
        template: "$"
final_space: true
version: 2
